### PR TITLE
You not need the last "}"

### PR DESCRIPTION
**Pull request by TonyDroidd**

### CODE REVIEW

**Comment by KyleTheHack3r** [comment]
Lol, the real thing isn't on GitHub... but thanks

**Comment by Gamecrafter** [comment]
@TonyDroidd Do you even know PHP? Of course you need the last brace! That last brace was to close up the class. This is an invalid solution.

**Comment by TonyDroidd** [comment]
This conversation is not with you, and stop picking on what you do not mind, please ;)
Ya me tienes hasta la madre.

**Comment by Bamuel** [comment]
I agree with @Gamecrafter 
he is correct

**Comment by TonyDroidd** [comment]
Kyle had a '}' extra in their code, that whas fixed.

**Comment by TonyDroidd** [comment]
other than the '}' which closes the code

**Comment by KyleTheHack3r** [comment]
Yes, I had some extra code which I removed and forgot to check it.

**Comment by Gamecrafter** [comment]
Oh. *facepalm* I hate it when people space it like that.

**Comment by TonyDroidd** [comment]
@Gamecrafter  You see? You have to inform about topic before speak ;)

**Pull request closed without merging**
